# Generated by Django 5.1.4 on 2024-12-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('forum_id', models.AutoField(primary_key=True, serialize=False)),
                ('forum_title', models.CharField(max_length=45)),
                ('forum_description', models.TextField()),
                ('forum_created_by', models.CharField(max_length=45)),
                ('forum_created_on', models.DateTimeField(auto_now_add=True)),
                ('forum_modified_on', models.DateTimeField(auto_now=True)),
                ('forum_modified_by', models.CharField(max_length=45)),
            ],
        ),
    ]
